//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub location: Option<String>,
    pub date: DateTimeWithTimeZone,
    pub start_time: DateTimeWithTimeZone,
    pub end_time: DateTimeWithTimeZone,
    pub notes: Option<String>,
    pub ensemble_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ensembles::Entity",
        from = "Column::EnsembleId",
        to = "super::ensembles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Ensembles,
}

impl Related<super::ensembles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ensembles.def()
    }
}
